//>>built
require({cache:{"dojox/gfx/shape":function(){define("./_base dojo/_base/lang dojo/_base/declare dojo/_base/kernel dojo/_base/sniff dojo/on dojo/_base/array dojo/dom-construct dojo/_base/Color ./matrix".split(" "),function(f,p,n,r,m,b,l,g,k,c){function q(a,c){if(!t)return a.splice(c,1);var e=a.length;if(e){for(;c<e;)a[c]=a[c+1],c++;a.length--}}var t=!!m("chrome"),h=f.shape={};h.Shape=n("dojox.gfx.shape.Shape",null,{constructor:function(){this.parentMatrix=this.parent=this.bbox=this.strokeStyle=this.fillStyle=
this.matrix=this.shape=this.rawNode=null;if(m("gfxRegistry")){var a=h.register(this);this.getUID=function(){return a}}},destroy:function(){m("gfxRegistry")&&h.dispose(this);this.rawNode&&"__gfxObject__"in this.rawNode&&(this.rawNode.__gfxObject__=null);this.rawNode=null},getNode:function(){return this.rawNode},getShape:function(){return this.shape},getTransform:function(){return this.matrix},getFill:function(){return this.fillStyle},getStroke:function(){return this.strokeStyle},getParent:function(){return this.parent},
getBoundingBox:function(){return this.bbox},getTransformedBoundingBox:function(){var a=this.getBoundingBox();if(!a)return null;var b=this._getRealMatrix();return[c.multiplyPoint(b,a.x,a.y),c.multiplyPoint(b,a.x+a.width,a.y),c.multiplyPoint(b,a.x+a.width,a.y+a.height),c.multiplyPoint(b,a.x,a.y+a.height)]},getEventSource:function(){return this.rawNode},setClip:function(a){this.clip=a},getClip:function(){return this.clip},setShape:function(a){this.shape=f.makeParameters(this.shape,a);this.bbox=null;
return this},setFill:function(a){if(!a)return this.fillStyle=null,this;var c=null;if("object"==typeof a&&"type"in a)switch(a.type){case "linear":c=f.makeParameters(f.defaultLinearGradient,a);break;case "radial":c=f.makeParameters(f.defaultRadialGradient,a);break;case "pattern":c=f.makeParameters(f.defaultPattern,a)}else c=f.normalizeColor(a);this.fillStyle=c;return this},setStroke:function(a){if(!a)return this.strokeStyle=null,this;if("string"==typeof a||p.isArray(a)||a instanceof k)a={color:a};a=
this.strokeStyle=f.makeParameters(f.defaultStroke,a);a.color=f.normalizeColor(a.color);return this},setTransform:function(a){this.matrix=c.clone(a?c.normalize(a):c.identity);return this._applyTransform()},_applyTransform:function(){return this},moveToFront:function(){var a=this.getParent();a&&(a._moveChildToFront(this),this._moveToFront());return this},moveToBack:function(){var a=this.getParent();a&&(a._moveChildToBack(this),this._moveToBack());return this},_moveToFront:function(){},_moveToBack:function(){},
applyRightTransform:function(a){return a?this.setTransform([this.matrix,a]):this},applyLeftTransform:function(a){return a?this.setTransform([a,this.matrix]):this},applyTransform:function(a){return a?this.setTransform([this.matrix,a]):this},removeShape:function(a){this.parent&&this.parent.remove(this,a);return this},_setParent:function(a,c){this.parent=a;return this._updateParentMatrix(c)},_updateParentMatrix:function(a){this.parentMatrix=a?c.clone(a):null;return this._applyTransform()},_getRealMatrix:function(){for(var a=
this.matrix,b=this.parent;b;)b.matrix&&(a=c.multiply(b.matrix,a)),b=b.parent;return a}});h._eventsProcessing={on:function(a,c){return b(this.getEventSource(),a,h.fixCallback(this,f.fixTarget,c))},connect:function(a,c,e){"on"==a.substring(0,2)&&(a=a.substring(2));return this.on(a,e?p.hitch(c,e):c)},disconnect:function(a){return a.remove()}};h.fixCallback=function(a,c,e,b){b||(b=e,e=null);if(p.isString(b)){e=e||r.global;if(!e[b])throw['dojox.gfx.shape.fixCallback: scope["',b,'"] is null (scope\x3d"',
e,'")'].join("");return function(f){return c(f,a)?e[b].apply(e,arguments||[]):void 0}}return e?function(f){return c(f,a)?b.apply(e,arguments||[]):void 0}:function(f){return c(f,a)?b.apply(e,arguments):void 0}};p.extend(h.Shape,h._eventsProcessing);h.Container={_init:function(){this.children=[];this._batch=0},openBatch:function(){return this},closeBatch:function(){return this},add:function(a){var c=a.getParent();c&&c.remove(a,!0);this.children.push(a);return a._setParent(this,this._getRealMatrix())},
remove:function(a,c){for(var e=0;e<this.children.length;++e)if(this.children[e]==a){c||(a.parent=null,a.parentMatrix=null);q(this.children,e);break}return this},clear:function(a){for(var c,e=0;e<this.children.length;++e)c=this.children[e],c.parent=null,c.parentMatrix=null,a&&c.destroy();this.children=[];return this},getBoundingBox:function(){if(this.children){var a=null;l.forEach(this.children,function(b){var e=b.getBoundingBox();e&&((b=b.getTransform())&&(e=c.multiplyRectangle(b,e)),a?(a.x=Math.min(a.x,
e.x),a.y=Math.min(a.y,e.y),a.endX=Math.max(a.endX,e.x+e.width),a.endY=Math.max(a.endY,e.y+e.height)):a={x:e.x,y:e.y,endX:e.x+e.width,endY:e.y+e.height})});a&&(a.width=a.endX-a.x,a.height=a.endY-a.y);return a}return null},_moveChildToFront:function(a){for(var c=0;c<this.children.length;++c)if(this.children[c]==a){q(this.children,c);this.children.push(a);break}return this},_moveChildToBack:function(a){for(var c=0;c<this.children.length;++c)if(this.children[c]==a){q(this.children,c);this.children.unshift(a);
break}return this}};h.Surface=n("dojox.gfx.shape.Surface",null,{constructor:function(){this._parent=this.rawNode=null;this._nodes=[];this._events=[]},destroy:function(){l.forEach(this._nodes,g.destroy);this._nodes=[];l.forEach(this._events,function(a){a&&a.remove()});this._events=[];this.rawNode=null;if(m("ie"))for(;this._parent.lastChild;)g.destroy(this._parent.lastChild);else this._parent.innerHTML="";this._parent=null},getEventSource:function(){return this.rawNode},_getRealMatrix:function(){return null},
isLoaded:!0,onLoad:function(a){},whenLoaded:function(a,c){var e=p.hitch(a,c);if(this.isLoaded)e(this);else b.once(this,"load",function(a){e(a)})}});p.extend(h.Surface,h._eventsProcessing);h.Rect=n("dojox.gfx.shape.Rect",h.Shape,{constructor:function(a){this.shape=f.getDefault("Rect");this.rawNode=a},getBoundingBox:function(){return this.shape}});h.Ellipse=n("dojox.gfx.shape.Ellipse",h.Shape,{constructor:function(a){this.shape=f.getDefault("Ellipse");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=
this.shape;this.bbox={x:a.cx-a.rx,y:a.cy-a.ry,width:2*a.rx,height:2*a.ry}}return this.bbox}});h.Circle=n("dojox.gfx.shape.Circle",h.Shape,{constructor:function(a){this.shape=f.getDefault("Circle");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}}return this.bbox}});h.Line=n("dojox.gfx.shape.Line",h.Shape,{constructor:function(a){this.shape=f.getDefault("Line");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=
this.shape;this.bbox={x:Math.min(a.x1,a.x2),y:Math.min(a.y1,a.y2),width:Math.abs(a.x2-a.x1),height:Math.abs(a.y2-a.y1)}}return this.bbox}});h.Polyline=n("dojox.gfx.shape.Polyline",h.Shape,{constructor:function(a){this.shape=f.getDefault("Polyline");this.rawNode=a},setShape:function(a,c){a&&a instanceof Array?(this.inherited(arguments,[{points:a}]),c&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):this.inherited(arguments,[a]);return this},_normalizePoints:function(){var a=
this.shape.points,c=a&&a.length;if(c&&"number"==typeof a[0]){for(var e=[],b=0;b<c;b+=2)e.push({x:a[b],y:a[b+1]});this.shape.points=e}},getBoundingBox:function(){if(!this.bbox&&this.shape.points.length){for(var a=this.shape.points,c=a.length,e=a[0],b=e.x,f=e.y,g=e.x,l=e.y,h=1;h<c;++h)e=a[h],b>e.x&&(b=e.x),g<e.x&&(g=e.x),f>e.y&&(f=e.y),l<e.y&&(l=e.y);this.bbox={x:b,y:f,width:g-b,height:l-f}}return this.bbox}});h.Image=n("dojox.gfx.shape.Image",h.Shape,{constructor:function(a){this.shape=f.getDefault("Image");
this.rawNode=a},getBoundingBox:function(){return this.shape},setStroke:function(){return this},setFill:function(){return this}});h.Text=n(h.Shape,{constructor:function(a){this.fontStyle=null;this.shape=f.getDefault("Text");this.rawNode=a},getFont:function(){return this.fontStyle},setFont:function(a){this.fontStyle="string"==typeof a?f.splitFontString(a):f.makeParameters(f.defaultFont,a);this._setFont();return this},getBoundingBox:function(){var a=null;this.getShape().text&&(a=f._base._computeTextBoundingBox(this));
return a}});h.Creator={createShape:function(a){switch(a.type){case f.defaultPath.type:return this.createPath(a);case f.defaultRect.type:return this.createRect(a);case f.defaultCircle.type:return this.createCircle(a);case f.defaultEllipse.type:return this.createEllipse(a);case f.defaultLine.type:return this.createLine(a);case f.defaultPolyline.type:return this.createPolyline(a);case f.defaultImage.type:return this.createImage(a);case f.defaultText.type:return this.createText(a);case f.defaultTextPath.type:return this.createTextPath(a)}return null},
createGroup:function(){return this.createObject(f.Group)},createRect:function(a){return this.createObject(f.Rect,a)},createEllipse:function(a){return this.createObject(f.Ellipse,a)},createCircle:function(a){return this.createObject(f.Circle,a)},createLine:function(a){return this.createObject(f.Line,a)},createPolyline:function(a){return this.createObject(f.Polyline,a)},createImage:function(a){return this.createObject(f.Image,a)},createText:function(a){return this.createObject(f.Text,a)},createPath:function(a){return this.createObject(f.Path,
a)},createTextPath:function(a){return this.createObject(f.TextPath,{}).setText(a)},createObject:function(a,c){return null}};return h})},"dojox/gfx/path":function(){define(["./_base","dojo/_base/lang","dojo/_base/declare","./matrix","./shape"],function(f,p,n,r,m){m=n("dojox.gfx.path.Path",m.Shape,{constructor:function(b){this.shape=p.clone(f.defaultPath);this.segments=[];this.tbbox=null;this.absolute=!0;this.last={};this.rawNode=b;this.segmented=!1},setAbsoluteMode:function(b){this._confirmSegmented();
this.absolute="string"==typeof b?"absolute"==b:b;return this},getAbsoluteMode:function(){this._confirmSegmented();return this.absolute},getBoundingBox:function(){this._confirmSegmented();return this.bbox&&"l"in this.bbox?{x:this.bbox.l,y:this.bbox.t,width:this.bbox.r-this.bbox.l,height:this.bbox.b-this.bbox.t}:null},_getRealBBox:function(){this._confirmSegmented();if(this.tbbox)return this.tbbox;var b=this.bbox,f=this._getRealMatrix();this.bbox=null;for(var g=0,k=this.segments.length;g<k;++g)this._updateWithSegment(this.segments[g],
f);f=this.bbox;this.bbox=b;return this.tbbox=f?[{x:f.l,y:f.t},{x:f.r,y:f.t},{x:f.r,y:f.b},{x:f.l,y:f.b}]:null},getLastPosition:function(){this._confirmSegmented();return"x"in this.last?this.last:null},_applyTransform:function(){this.tbbox=null;return this.inherited(arguments)},_updateBBox:function(b,f,g){g&&(f=r.multiplyPoint(g,b,f),b=f.x,f=f.y);this.bbox&&"l"in this.bbox?(this.bbox.l>b&&(this.bbox.l=b),this.bbox.r<b&&(this.bbox.r=b),this.bbox.t>f&&(this.bbox.t=f),this.bbox.b<f&&(this.bbox.b=f)):
this.bbox={l:b,b:f,r:b,t:f}},_updateWithSegment:function(b,l){var g=b.args,k=g.length,c;switch(b.action){case "M":case "L":case "C":case "S":case "Q":case "T":for(c=0;c<k;c+=2)this._updateBBox(g[c],g[c+1],l);this.last.x=g[k-2];this.last.y=g[k-1];this.absolute=!0;break;case "H":for(c=0;c<k;++c)this._updateBBox(g[c],this.last.y,l);this.last.x=g[k-1];this.absolute=!0;break;case "V":for(c=0;c<k;++c)this._updateBBox(this.last.x,g[c],l);this.last.y=g[k-1];this.absolute=!0;break;case "m":c=0;"x"in this.last||
(this._updateBBox(this.last.x=g[0],this.last.y=g[1],l),c=2);for(;c<k;c+=2)this._updateBBox(this.last.x+=g[c],this.last.y+=g[c+1],l);this.absolute=!1;break;case "l":case "t":for(c=0;c<k;c+=2)this._updateBBox(this.last.x+=g[c],this.last.y+=g[c+1],l);this.absolute=!1;break;case "h":for(c=0;c<k;++c)this._updateBBox(this.last.x+=g[c],this.last.y,l);this.absolute=!1;break;case "v":for(c=0;c<k;++c)this._updateBBox(this.last.x,this.last.y+=g[c],l);this.absolute=!1;break;case "c":for(c=0;c<k;c+=6)this._updateBBox(this.last.x+
g[c],this.last.y+g[c+1],l),this._updateBBox(this.last.x+g[c+2],this.last.y+g[c+3],l),this._updateBBox(this.last.x+=g[c+4],this.last.y+=g[c+5],l);this.absolute=!1;break;case "s":case "q":for(c=0;c<k;c+=4)this._updateBBox(this.last.x+g[c],this.last.y+g[c+1],l),this._updateBBox(this.last.x+=g[c+2],this.last.y+=g[c+3],l);this.absolute=!1;break;case "A":for(c=0;c<k;c+=7)this._updateBBox(g[c+5],g[c+6],l);this.last.x=g[k-2];this.last.y=g[k-1];this.absolute=!0;break;case "a":for(c=0;c<k;c+=7)this._updateBBox(this.last.x+=
g[c+5],this.last.y+=g[c+6],l);this.absolute=!1}b=[b.action];for(c=0;c<k;++c)b.push(f.formatNumber(g[c],!0));if("string"==typeof this.shape.path)this.shape.path+=b.join("");else for(c=0,k=b.length;c<k;++c)this.shape.path.push(b[c])},_validSegments:{m:2,l:2,h:1,v:1,c:6,s:4,q:4,t:2,a:7,z:0},_pushSegment:function(b,f){this.tbbox=null;var g=this._validSegments[b.toLowerCase()];"number"==typeof g&&(g?f.length>=g&&(b={action:b,args:f.slice(0,f.length-f.length%g)},this.segments.push(b),this._updateWithSegment(b)):
(b={action:b,args:[]},this.segments.push(b),this._updateWithSegment(b)))},_collectArgs:function(b,f){for(var g=0;g<f.length;++g){var k=f[g];"boolean"==typeof k?b.push(k?1:0):"number"==typeof k?b.push(k):k instanceof Array?this._collectArgs(b,k):"x"in k&&"y"in k&&b.push(k.x,k.y)}},moveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"M":"m",b);return this},lineTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);
this._pushSegment(this.absolute?"L":"l",b);return this},hLineTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"H":"h",b);return this},vLineTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"V":"v",b);return this},curveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"C":"c",b);return this},smoothCurveTo:function(){this._confirmSegmented();
var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"S":"s",b);return this},qCurveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"Q":"q",b);return this},qSmoothCurveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"T":"t",b);return this},arcTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"A":
"a",b);return this},closePath:function(){this._confirmSegmented();this._pushSegment("Z",[]);return this},_confirmSegmented:function(){if(!this.segmented){var b=this.shape.path;this.shape.path=[];this._setPath(b);this.shape.path=this.shape.path.join("");this.segmented=!0}},_setPath:function(b){b=p.isArray(b)?b:b.match(f.pathSvgRegExp);this.segments=[];this.absolute=!0;this.bbox={};this.last={};if(b){for(var l="",g=[],k=b.length,c=0;c<k;++c){var m=b[c],n=parseFloat(m);isNaN(n)?(l&&this._pushSegment(l,
g),g=[],l=m):g.push(n)}this._pushSegment(l,g)}},setShape:function(b){this.inherited(arguments,["string"==typeof b?{path:b}:b]);this.segmented=!1;this.segments=[];f.lazyPathSegmentation||this._confirmSegmented();return this},_2PI:2*Math.PI});n=n("dojox.gfx.path.TextPath",m,{constructor:function(b){"text"in this||(this.text=p.clone(f.defaultTextPath));"fontStyle"in this||(this.fontStyle=p.clone(f.defaultFont))},getText:function(){return this.text},setText:function(b){this.text=f.makeParameters(this.text,
"string"==typeof b?{text:b}:b);this._setText();return this},getFont:function(){return this.fontStyle},setFont:function(b){this.fontStyle="string"==typeof b?f.splitFontString(b):f.makeParameters(f.defaultFont,b);this._setFont();return this}});return f.path={Path:m,TextPath:n}})},"*noref":1}});
define("dojox/gfx/svg","dojo/_base/lang dojo/_base/sniff dojo/_base/window dojo/dom dojo/_base/declare dojo/_base/array dojo/dom-geometry dojo/dom-attr dojo/_base/Color ./_base ./shape ./path".split(" "),function(f,p,n,r,m,b,l,g,k,c,q,t){function h(d,a){return n.doc.createElementNS?n.doc.createElementNS(d,a):n.doc.createElement(a)}function a(d,a,c,e){return d.setAttributeNS?d.setAttributeNS(a,c,e):d.setAttribute(c,e)}function w(d){return e.useSvgWeb?n.doc.createTextNode(d,!0):n.doc.createTextNode(d)}
var e=c.svg={};e.useSvgWeb="undefined"!=typeof window.svgweb;var y=navigator.userAgent,z=p("ios"),x=p("android"),A=p("chrome")||x&&4<=x?"auto":"optimizeLegibility";e.xmlns={xlink:"http://www.w3.org/1999/xlink",svg:"http://www.w3.org/2000/svg"};e.getRef=function(d){return d&&"none"!=d?d.match(/^url\(#.+\)$/)?r.byId(d.slice(5,-1)):d.match(/^#dojoUnique\d+$/)?r.byId(d.slice(1)):null:null};e.dasharray={solid:"none",shortdash:[4,1],shortdot:[1,1],shortdashdot:[4,1,1,1],shortdashdotdot:[4,1,1,1,1,1],dot:[1,
3],dash:[4,3],longdash:[8,3],dashdot:[4,3,1,3],longdashdot:[8,3,1,3],longdashdotdot:[8,3,1,3,1,3]};var B=0;e.Shape=m("dojox.gfx.svg.Shape",q.Shape,{destroy:function(){if(this.fillStyle&&"type"in this.fillStyle){var d=this.rawNode.getAttribute("fill");(d=e.getRef(d))&&d.parentNode.removeChild(d)}this.clip&&(d=this.rawNode.getAttribute("clip-path"))&&(d=r.byId(d.match(/gfx_clip[\d]+/)[0]))&&d.parentNode.removeChild(d);q.Shape.prototype.destroy.apply(this,arguments)},setFill:function(d){if(!d)return this.fillStyle=
null,this.rawNode.setAttribute("fill","none"),this.rawNode.setAttribute("fill-opacity",0),this;var a,e=function(d){this.setAttribute(d,a[d].toFixed(8))};if("object"==typeof d&&"type"in d){switch(d.type){case "linear":a=c.makeParameters(c.defaultLinearGradient,d);d=this._setFillObject(a,"linearGradient");b.forEach(["x1","y1","x2","y2"],e,d);break;case "radial":a=c.makeParameters(c.defaultRadialGradient,d);d=this._setFillObject(a,"radialGradient");b.forEach(["cx","cy","r"],e,d);break;case "pattern":a=
c.makeParameters(c.defaultPattern,d),d=this._setFillObject(a,"pattern"),b.forEach(["x","y","width","height"],e,d)}this.fillStyle=a;return this}this.fillStyle=a=c.normalizeColor(d);this.rawNode.setAttribute("fill",a.toCss());this.rawNode.setAttribute("fill-opacity",a.a);this.rawNode.setAttribute("fill-rule","evenodd");return this},setStroke:function(d){var a=this.rawNode;if(!d)return this.strokeStyle=null,a.setAttribute("stroke","none"),a.setAttribute("stroke-opacity",0),this;if("string"==typeof d||
f.isArray(d)||d instanceof k)d={color:d};d=this.strokeStyle=c.makeParameters(c.defaultStroke,d);d.color=c.normalizeColor(d.color);if(d){var b=0>d.width?0:d.width;a.setAttribute("stroke",d.color.toCss());a.setAttribute("stroke-opacity",d.color.a);a.setAttribute("stroke-width",b);a.setAttribute("stroke-linecap",d.cap);"number"==typeof d.join?(a.setAttribute("stroke-linejoin","miter"),a.setAttribute("stroke-miterlimit",d.join)):a.setAttribute("stroke-linejoin",d.join);var g=d.style.toLowerCase();g in
e.dasharray&&(g=e.dasharray[g]);if(g instanceof Array){var g=f._toArray(g),h;for(h=0;h<g.length;++h)g[h]*=b;if("butt"!=d.cap){for(h=0;h<g.length;h+=2)g[h]-=b,1>g[h]&&(g[h]=1);for(h=1;h<g.length;h+=2)g[h]+=b}g=g.join(",")}a.setAttribute("stroke-dasharray",g);a.setAttribute("dojoGfxStrokeStyle",d.style)}return this},_getParentSurface:function(){for(var d=this.parent;d&&!(d instanceof c.Surface);d=d.parent);return d},_setFillObject:function(d,b){var f=e.xmlns.svg;this.fillStyle=d;var u=this._getParentSurface().defNode,
g=this.rawNode.getAttribute("fill");if(g=e.getRef(g))if(g.tagName.toLowerCase()!=b.toLowerCase()){var k=g.id;g.parentNode.removeChild(g);g=h(f,b);g.setAttribute("id",k);u.appendChild(g)}else for(;g.childNodes.length;)g.removeChild(g.lastChild);else g=h(f,b),g.setAttribute("id",c._base._getUniqueId()),u.appendChild(g);if("pattern"==b)g.setAttribute("patternUnits","userSpaceOnUse"),f=h(f,"image"),f.setAttribute("x",0),f.setAttribute("y",0),f.setAttribute("width",(0>d.width?0:d.width).toFixed(8)),f.setAttribute("height",
(0>d.height?0:d.height).toFixed(8)),a(f,e.xmlns.xlink,"xlink:href",d.src),g.appendChild(f);else for(g.setAttribute("gradientUnits","userSpaceOnUse"),b=0;b<d.colors.length;++b){var u=d.colors[b],k=h(f,"stop"),l=u.color=c.normalizeColor(u.color);k.setAttribute("offset",u.offset.toFixed(8));k.setAttribute("stop-color",l.toCss());k.setAttribute("stop-opacity",l.a);g.appendChild(k)}this.rawNode.setAttribute("fill","url(#"+g.getAttribute("id")+")");this.rawNode.removeAttribute("fill-opacity");this.rawNode.setAttribute("fill-rule",
"evenodd");return g},_applyTransform:function(){if(this.matrix){var d=this.matrix;this.rawNode.setAttribute("transform","matrix("+d.xx.toFixed(8)+","+d.yx.toFixed(8)+","+d.xy.toFixed(8)+","+d.yy.toFixed(8)+","+d.dx.toFixed(8)+","+d.dy.toFixed(8)+")")}else this.rawNode.removeAttribute("transform");return this},setRawNode:function(d){d=this.rawNode=d;"image"!=this.shape.type&&d.setAttribute("fill","none");d.setAttribute("fill-opacity",0);d.setAttribute("stroke","none");d.setAttribute("stroke-opacity",
0);d.setAttribute("stroke-width",1);d.setAttribute("stroke-linecap","butt");d.setAttribute("stroke-linejoin","miter");d.setAttribute("stroke-miterlimit",4);d.__gfxObject__=this},setShape:function(d){this.shape=c.makeParameters(this.shape,d);for(var a in this.shape)if("type"!=a){d=this.shape[a];if("width"===a||"height"===a)d=0>d?0:d;this.rawNode.setAttribute(a,d)}this.bbox=null;return this},_moveToFront:function(){this.rawNode.parentNode.appendChild(this.rawNode);return this},_moveToBack:function(){this.rawNode.parentNode.insertBefore(this.rawNode,
this.rawNode.parentNode.firstChild);return this},setClip:function(d){this.inherited(arguments);var a=d?"width"in d?"rect":"cx"in d?"ellipse":"points"in d?"polyline":"d"in d?"path":null:null;if(d&&!a)return this;"polyline"===a&&(d=f.clone(d),d.points=d.points.join(","));var c,b=g.get(this.rawNode,"clip-path");b&&(c=r.byId(b.match(/gfx_clip[\d]+/)[0]))&&c.removeChild(c.childNodes[0]);d?(c?(a=h(e.xmlns.svg,a),c.appendChild(a)):(b="gfx_clip"+ ++B,this.rawNode.setAttribute("clip-path","url(#"+b+")"),c=
h(e.xmlns.svg,"clipPath"),a=h(e.xmlns.svg,a),c.appendChild(a),this.rawNode.parentNode.insertBefore(c,this.rawNode),g.set(c,"id",b)),g.set(a,d)):(this.rawNode.removeAttribute("clip-path"),c&&c.parentNode.removeChild(c));return this},_removeClipNode:function(){var d,a=g.get(this.rawNode,"clip-path");a&&(d=r.byId(a.match(/gfx_clip[\d]+/)[0]))&&d.parentNode.removeChild(d);return d}});e.Group=m("dojox.gfx.svg.Group",e.Shape,{constructor:function(){q.Container._init.call(this)},setRawNode:function(a){this.rawNode=
a;this.rawNode.__gfxObject__=this},destroy:function(){this.clear(!0);e.Shape.prototype.destroy.apply(this,arguments)}});e.Group.nodeType="g";e.Rect=m("dojox.gfx.svg.Rect",[e.Shape,q.Rect],{setShape:function(a){this.shape=c.makeParameters(this.shape,a);this.bbox=null;for(var d in this.shape)if("type"!=d&&"r"!=d){a=this.shape[d];if("width"===d||"height"===d)a=0>a?0:a;this.rawNode.setAttribute(d,a)}null!=this.shape.r&&(this.rawNode.setAttribute("ry",this.shape.r),this.rawNode.setAttribute("rx",this.shape.r));
return this}});e.Rect.nodeType="rect";e.Ellipse=m("dojox.gfx.svg.Ellipse",[e.Shape,q.Ellipse],{});e.Ellipse.nodeType="ellipse";e.Circle=m("dojox.gfx.svg.Circle",[e.Shape,q.Circle],{});e.Circle.nodeType="circle";e.Line=m("dojox.gfx.svg.Line",[e.Shape,q.Line],{});e.Line.nodeType="line";e.Polyline=m("dojox.gfx.svg.Polyline",[e.Shape,q.Polyline],{setShape:function(a,b){a&&a instanceof Array?(this.shape=c.makeParameters(this.shape,{points:a}),b&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):
this.shape=c.makeParameters(this.shape,a);this.bbox=null;this._normalizePoints();a=[];b=this.shape.points;for(var d=0;d<b.length;++d)a.push(b[d].x.toFixed(8),b[d].y.toFixed(8));this.rawNode.setAttribute("points",a.join(" "));return this}});e.Polyline.nodeType="polyline";e.Image=m("dojox.gfx.svg.Image",[e.Shape,q.Image],{setShape:function(d){this.shape=c.makeParameters(this.shape,d);this.bbox=null;d=this.rawNode;for(var b in this.shape)if("type"!=b&&"src"!=b){var f=this.shape[b];if("width"===b||"height"===
b)f=0>f?0:f;d.setAttribute(b,f)}d.setAttribute("preserveAspectRatio","none");a(d,e.xmlns.xlink,"xlink:href",this.shape.src);d.__gfxObject__=this;return this}});e.Image.nodeType="image";e.Text=m("dojox.gfx.svg.Text",[e.Shape,q.Text],{setShape:function(a){this.shape=c.makeParameters(this.shape,a);this.bbox=null;a=this.rawNode;var d=this.shape;a.setAttribute("x",d.x);a.setAttribute("y",d.y);a.setAttribute("text-anchor",d.align);a.setAttribute("text-decoration",d.decoration);a.setAttribute("rotate",d.rotated?
90:0);a.setAttribute("kerning",d.kerning?"auto":0);a.setAttribute("text-rendering",A);a.firstChild?a.firstChild.nodeValue=d.text:a.appendChild(w(d.text));return this},getTextWidth:function(){var a=this.rawNode,c=a.parentNode,a=a.cloneNode(!0);a.style.visibility="hidden";var b=0,e=a.firstChild.nodeValue;c.appendChild(a);if(""!=e)for(;!b;)b=a.getBBox?parseInt(a.getBBox().width):68;c.removeChild(a);return b},getBoundingBox:function(){var a=null;if(this.getShape().text)try{a=this.rawNode.getBBox()}catch(u){a=
{x:0,y:0,width:0,height:0}}return a}});e.Text.nodeType="text";e.Path=m("dojox.gfx.svg.Path",[e.Shape,t.Path],{_updateWithSegment:function(a){this.inherited(arguments);"string"==typeof this.shape.path&&this.rawNode.setAttribute("d",this.shape.path)},setShape:function(a){this.inherited(arguments);this.shape.path?this.rawNode.setAttribute("d",this.shape.path):this.rawNode.removeAttribute("d");return this}});e.Path.nodeType="path";e.TextPath=m("dojox.gfx.svg.TextPath",[e.Shape,t.TextPath],{_updateWithSegment:function(a){this.inherited(arguments);
this._setTextPath()},setShape:function(a){this.inherited(arguments);this._setTextPath();return this},_setTextPath:function(){if("string"==typeof this.shape.path){var d=this.rawNode;if(!d.firstChild){var b=h(e.xmlns.svg,"textPath"),f=w("");b.appendChild(f);d.appendChild(b)}b=(b=d.firstChild.getAttributeNS(e.xmlns.xlink,"href"))&&e.getRef(b);if(!b&&(f=this._getParentSurface())){var f=f.defNode,b=h(e.xmlns.svg,"path"),g=c._base._getUniqueId();b.setAttribute("id",g);f.appendChild(b);a(d.firstChild,e.xmlns.xlink,
"xlink:href","#"+g)}b&&b.setAttribute("d",this.shape.path)}},_setText:function(){var a=this.rawNode;if(!a.firstChild){var b=h(e.xmlns.svg,"textPath"),c=w("");b.appendChild(c);a.appendChild(b)}a=a.firstChild;b=this.text;a.setAttribute("alignment-baseline","middle");switch(b.align){case "middle":a.setAttribute("text-anchor","middle");a.setAttribute("startOffset","50%");break;case "end":a.setAttribute("text-anchor","end");a.setAttribute("startOffset","100%");break;default:a.setAttribute("text-anchor",
"start"),a.setAttribute("startOffset","0%")}a.setAttribute("baseline-shift","0.5ex");a.setAttribute("text-decoration",b.decoration);a.setAttribute("rotate",b.rotated?90:0);a.setAttribute("kerning",b.kerning?"auto":0);a.firstChild.data=b.text}});e.TextPath.nodeType="text";var C=534<function(){var a=/WebKit\/(\d*)/.exec(y);return a?a[1]:0}();e.Surface=m("dojox.gfx.svg.Surface",q.Surface,{constructor:function(){q.Container._init.call(this)},destroy:function(){q.Container.clear.call(this,!0);this.defNode=
null;this.inherited(arguments)},setDimensions:function(a,b){if(!this.rawNode)return this;a=0>a?0:a;b=0>b?0:b;this.rawNode.setAttribute("width",a);this.rawNode.setAttribute("height",b);C&&(this.rawNode.style.width=a,this.rawNode.style.height=b);return this},getDimensions:function(){return this.rawNode?{width:c.normalizedLength(this.rawNode.getAttribute("width")),height:c.normalizedLength(this.rawNode.getAttribute("height"))}:null}});e.createSurface=function(a,b,f){var d=new e.Surface;d.rawNode=h(e.xmlns.svg,
"svg");d.rawNode.setAttribute("overflow","hidden");b&&d.rawNode.setAttribute("width",0>b?0:b);f&&d.rawNode.setAttribute("height",0>f?0:f);b=h(e.xmlns.svg,"defs");d.rawNode.appendChild(b);d.defNode=b;d._parent=r.byId(a);d._parent.appendChild(d.rawNode);c._base._fixMsTouchAction(d);return d};p={_setFont:function(){var a=this.fontStyle;this.rawNode.setAttribute("font-style",a.style);this.rawNode.setAttribute("font-variant",a.variant);this.rawNode.setAttribute("font-weight",a.weight);this.rawNode.setAttribute("font-size",
a.size);this.rawNode.setAttribute("font-family",a.family)}};var v=q.Container;m=e.Container={openBatch:function(){if(!this._batch){var a;a=e.useSvgWeb?n.doc.createDocumentFragment(!0):n.doc.createDocumentFragment();this.fragment=a}++this._batch;return this},closeBatch:function(){this._batch=0<this._batch?--this._batch:0;this.fragment&&!this._batch&&(this.rawNode.appendChild(this.fragment),delete this.fragment);return this},add:function(a){this!=a.getParent()&&(this.fragment?this.fragment.appendChild(a.rawNode):
this.rawNode.appendChild(a.rawNode),v.add.apply(this,arguments),a.setClip(a.clip));return this},remove:function(a,b){this==a.getParent()&&(this.rawNode==a.rawNode.parentNode&&this.rawNode.removeChild(a.rawNode),this.fragment&&this.fragment==a.rawNode.parentNode&&this.fragment.removeChild(a.rawNode),a._removeClipNode(),v.remove.apply(this,arguments));return this},clear:function(){for(var a=this.rawNode;a.lastChild;)a.removeChild(a.lastChild);var b=this.defNode;if(b){for(;b.lastChild;)b.removeChild(b.lastChild);
a.appendChild(b)}return v.clear.apply(this,arguments)},getBoundingBox:v.getBoundingBox,_moveChildToFront:v._moveChildToFront,_moveChildToBack:v._moveChildToBack};t=e.Creator={createObject:function(a,b){if(!this.rawNode)return null;var d=new a;a=h(e.xmlns.svg,a.nodeType);d.setRawNode(a);d.setShape(b);this.add(d);return d}};f.extend(e.Text,p);f.extend(e.TextPath,p);f.extend(e.Group,m);f.extend(e.Group,q.Creator);f.extend(e.Group,t);f.extend(e.Surface,m);f.extend(e.Surface,q.Creator);f.extend(e.Surface,
t);e.fixTarget=function(a,b){a.gfxTarget||(a.gfxTarget=z&&a.target.wholeText?a.target.parentElement.__gfxObject__:a.target.__gfxObject__);return!0};e.useSvgWeb&&(e.createSurface=function(a,b,f){var d=new e.Surface;b=0>b?0:b;f=0>f?0:f;if(!b||!f){var g=l.position(a);b=b||g.w;f=f||g.h}a=r.byId(a);var g=a.id?a.id+"_svgweb":c._base._getUniqueId(),k=h(e.xmlns.svg,"svg");k.id=g;k.setAttribute("width",b);k.setAttribute("height",f);svgweb.appendChild(k,a);k.addEventListener("SVGLoad",function(){d.rawNode=
this;d.isLoaded=!0;var a=h(e.xmlns.svg,"defs");d.rawNode.appendChild(a);d.defNode=a;if(d.onLoad)d.onLoad(d)},!1);d.isLoaded=!1;return d},e.Surface.extend({destroy:function(){var a=this.rawNode;svgweb.removeChild(a,a.parentNode)}}),p={connect:function(a,b,c){"on"===a.substring(0,2)&&(a=a.substring(2));c=2==arguments.length?b:f.hitch(b,c);this.getEventSource().addEventListener(a,c,!1);return[this,a,c]},disconnect:function(a){this.getEventSource().removeEventListener(a[1],a[2],!1);delete a[0]}},f.extend(e.Shape,
p),f.extend(e.Surface,p));return e});