# Generated by Django 3.1.2 on 2021-04-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0013_auto_20201203_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebapplicationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participantid', models.CharField(blank=True, max_length=100, null=True)),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('q4', models.IntegerField(blank=True, null=True)),
                ('q5', models.IntegerField(blank=True, null=True)),
                ('q6', models.IntegerField(blank=True, null=True)),
                ('q7', models.IntegerField(blank=True, null=True)),
                ('q8', models.IntegerField(blank=True, null=True)),
                ('q9', models.IntegerField(blank=True, null=True)),
                ('q10', models.IntegerField(blank=True, null=True)),
                ('q11', models.IntegerField(blank=True, null=True)),
                ('q12', models.IntegerField(blank=True, null=True)),
                ('q13', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexpsurveymodel',
            name='q18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='q9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
